setwd("~/Documents/TraumaMatrix/CausalInference/Simulations/causal-inference-missing/")
source("./load.R")


# >= 13/08: "dlvm" = {confounders are X}, "dlvm2"/"dlvm3" = {confounders are Z}, 
#           "linear1"/"linear2" =  = {confounders are X}, "mf" = {confounders are Z}

data.dir <- "./MissDeepCausal/Synthetic/Data/"
rdata.dir <- "./MissDeepCausal/Synthetic/RData/"
fig.dir <- "./MissDeepCausal/Synthetic/Figures/iclr_octobre/"

######## Set options

link <- "nonlinear3" # either "linear1"/"linear2"/"linear3"/"nonlinear3" (for "linear1","linear2","mf" setting) or "linear0"/"nonlinear3" (for "dlvm" setting)
setting <- "dlvm2" # either "linear1", "linear2", "mf", "dlvm", "dlvm2" "dlvm3" 
sd <- 0.1 # noise sd for data generation

n <- 5000 # number of realizations
p <- 10 # dimension of the ambient space
d <- 3 # dimension of the latent space
h <- 5 # dimension of hidden units
h.miwae <- 128 # dimension of hidden units used for estimation by MIWAE
add_mask <- "_mask" # either "_mask" or ""  
cit2 <- FALSE
cio2 <- FALSE

mi.m <- 10 # number of multiple imputations
prop.missing = 0.1 # proportion of missing values

num.samples.sir <- 200

###########################################################################
# Load data generated by running script missdeepcausal_comparisons_ate.R
###########################################################################
library(RColorBrewer)
myColors <- brewer.pal(3,"Set2")
names(myColors) <- c("","grf","glm")
colScale <- scale_fill_manual(name = "",values = rev(myColors))

configurations <- data.frame(rbind(
    cbind("2019-09-25", "nonlinear3", "dlvm2", 10000, 10, 0, 10, FALSE, "","", "_", "grf", 200, 1, 4, 0.99, 1.21),
    cbind("2019-09-25", "nonlinear3", "dlvm2", 10000, 10, 0.1, 10, FALSE, "","", "_", "grf", 200, 0, 4, 0.99, 1.21),
    cbind("2019-09-25", "nonlinear3", "dlvm2", 10000, 10, 0.3, 10, FALSE, "","", "_", "grf", 200, 0, 4, 0.99, 1.21),
    cbind("2019-09-25", "linear3", "mf", 10000, 10, 0, 10, FALSE, "","", "_", "grf", 200, 1, 4, 0.95, 1.11),
    cbind("2019-09-25", "linear3", "mf", 10000, 10, 0.1, 10, FALSE, "","", "_", "grf", 200, 0, 4, 0.94, 1.11),
    cbind("2019-09-25", "linear3", "mf", 10000, 10, 0.3, 10, FALSE, "","", "_", "grf", 200, 0, 4, 0.94, 1.11),
    cbind("2019-09-25", "linear0", "dlvm2", 10000, 10, 0, 10, FALSE, "","", "_", "grf", 200, 0, 4, 0.75, 1.01),
    cbind("2019-09-25", "linear0", "dlvm2", 10000, 10, 0.1, 10, FALSE, "","", "_", "grf", 200, 0, 4, 0.75, 1.01),
    cbind("2019-09-25", "linear0", "dlvm2", 10000, 10, 0.3, 10, FALSE, "","", "_", "grf", 200, 0, 4, 0.75, 1.01),
    cbind("2019-09-25", "nonlinear3", "mf", 10000, 10, 0, 10, FALSE, "","", "_", "grf", 200, 0, 4, 0.99, 2),#6.01),
    cbind("2019-09-25", "nonlinear3", "mf", 10000, 10, 0.1, 10, FALSE, "","", "_", "grf", 200, 0, 4, 0.99, 2),#6.01),
    cbind("2019-09-25", "nonlinear3", "mf", 10000, 10, 0.3, 10, FALSE, "","", "_", "grf", 200, 0, 4, 0.99, 2),#6.01),
    # cbind("2019-10-01", "nonlinear3", "dlvm2", 10000, 20, 0, 10, FALSE, "","", "_", "grf", 200, 1, 4, 0.99, 1.21),
    # cbind("2019-10-01", "nonlinear3", "dlvm2", 10000, 20, 0.1, 10, FALSE, "","", "_", "grf", 200, 0, 4, 0.99, 1.21),
    # cbind("2019-10-01", "nonlinear3", "dlvm2", 10000, 20, 0.3, 10, FALSE, "","", "_", "grf", 200, 0, 4, 0.99, 1.21),
    # cbind("2019-10-01", "linear3", "mf", 10000, 20, 0, 10, FALSE, "","", "_", "grf", 200, 0, 4, 0.94, 1.11),
    # cbind("2019-10-01", "linear3", "mf", 10000, 20, 0.1, 10, FALSE, "", "","_", "grf", 200, 0, 4, 0.94, 1.11),
    # cbind("2019-10-01", "linear3", "mf", 10000, 20, 0.3, 10, FALSE, "", "","_", "grf", 200, 0, 4, 0.94, 1.11),
    cbind("2019-10-03", "nonlinear3", "dlvm2", 10000, 20, 0, 10, FALSE, "", "_WY", "_", "grf", 200, 0, 4, 0.99, 1.21),
    cbind("2019-10-03", "nonlinear3", "dlvm2", 10000, 20, 0.1, 10, FALSE, "","_WY", "_", "grf", 200, 0, 4, 0.99, 1.21),
    cbind("2019-10-03", "nonlinear3", "dlvm2", 10000, 20, 0.3, 10, FALSE, "","_WY", "_", "grf", 200, 0, 4, 0.99, 1.21),
    cbind("2019-10-03", "linear0", "dlvm2", 10000, 20, 0, 10, FALSE, "", "_WY", "_", "grf", 200, 0, 4, 0.75, 1.01),
    cbind("2019-10-03", "linear0", "dlvm2", 10000, 20, 0.1, 10, FALSE, "","_WY", "_", "grf", 200, 0, 4, 0.75, 1.01),
    cbind("2019-10-03", "linear0", "dlvm2", 10000, 20, 0.3, 10, FALSE, "","_WY", "_", "grf", 200, 0, 4, 0.75, 1.01)))
  
# results for smaller sample sizes are also partly available
##cbind("nonlinear3", "dlvm2", 5000, 0, 10, FALSE, "", "", "grf", 200, 0, 4),
#cbind("nonlinear3", "dlvm2", 5000, 0.1, 10, FALSE, "", "_", "grf", 200, 0, 4),
#cbind("nonlinear3", "dlvm2", 5000, 0.3, 10, FALSE, "", "_", "grf", 200, 0, 4),
##cbind("linear0", "dlvm2", 5000, 0, 10, FALSE, "", "_", "grf", 200, 0, 4),
#cbind("linear0", "dlvm2", 5000, 0.1, 10, FALSE, "", "_", "grf", 200, 0, 4),
#cbind("linear0", "dlvm2", 5000, 0.3, 10, FALSE, "", "_", "grf", 200, 0, 4),
##cbind("linear3", "mf", 5000, 0, 10, FALSE, "", "_", "grf", 200, 0, 4),
#cbind("linear3", "mf", 5000, 0.1, 10, FALSE, "", "_", "grf", 200, 0, 4),
#cbind("linear3", "mf", 5000, 0.3, 10, FALSE, "", "_", "grf", 200, 0, 4),

colnames(configurations) <- c("file_date","link","setting","n","p",
                              "prop.missing",
                              "d.miwae","cit2", 
                              "use.w", "use.wy", "add_mask", "forest", "num.samples.sir", 
                              "seed.min", "seed.max",
                              "y.min", "y.max")

configurations[,c("file_date", "link","setting","add_mask",
                  "use.w","use.wy", "forest")] <- apply(configurations[,c("file_date","link","setting","add_mask","use.w","use.wy", "forest")], 2, as.character)
configurations[,c("prop.missing","n", "p",
                  "num.samples.sir",
                  "seed.min","seed.max",
                  "d.miwae",
                  "y.min", "y.max")] <- apply(configurations[,c("prop.missing","n","p",
                                                                "num.samples.sir",
                                                                "seed.min","seed.max",
                                                                "d.miwae",
                                                                "y.min", "y.max")], 2, as.numeric)
configurations$cit2 <- as.logical(configurations$cit2)


for (i in 7:7){#1:dim(configurations)[1]){#dim(configurations)[1]){
  conf <- configurations[i,]
  print(conf)
  dr.res <- c()
  ipw.res <- c()
  seed_seq <- conf$seed.min:conf$seed.max
  #if (i%in%c(1,3)) {seed_seq <- c(0,1,2,4)}
  for (seed in seed_seq){
    load(file = paste0(rdata.dir, conf$file_date,
                       "_",conf$link,"_",conf$setting, "_n", conf$n, "_p", conf$p, "_d", d, 
                       conf$use.wy,conf$use.w,"_dmiwae", conf$d.miwae, "_hmiwae", h.miwae,
                       conf$add_mask,
                       "_sir", conf$num.samples.sir,
                       "_propNA", format(round(conf$prop.missing, 2), nsmall=2),
                       "_cit2", as.logical(conf$cit2), "_ci2Impmice", 
                       "_forest", conf$forest,
                       "_results_dr_ipw_seed",seed,".RData"))
    dr.loglin$dr <- as.double(as.character(dr.loglin$dr))
    dr.loglin$se <- as.double(as.character(dr.loglin$se))
    
    dr.res <- rbind(dr.res, dr.loglin)
  }
  
  dr.res <- dr.res[order(as.character(dr.res$method)),] 
  
  dr.res <- dr.res %>%
    filter((as.character(method) %in% c("loglin.mice.wy", "loglin.mf.cv", "loglin.miwae", 
                                        "loglin.Z_true", "loglin.miwae.agg",
                                        "grf.mice.wy", "grf.mf.cv", "grf.miwae", "grf.mia",
                                        "grf.Z_true", "grf.miwae.agg")))
  dr.res$method <- droplevels(dr.res$method)
  if (conf$setting %in% c("mf", "dlvm2", "dlvm3")){
    levels(dr.res$method) <- list("loglin.MICE" = "loglin.mice.wy",
                                  "loglin.MF" = "loglin.mf.cv",
                                  "loglin.MDC.process" = "loglin.miwae", 
                                  "loglin.Z_true" = "loglin.Z_true",
                                  "loglin.MDC.mi" = "loglin.miwae.agg",
                                  "loglin.MDC" = "loglin.miwae.zmul", 
                                  "grf.MICE" = "grf.mice.wy",
                                  "grf.MF" = "grf.mf.cv",
                                  "grf.MDC.process" = "grf.miwae",
                                  "grf.MIA" = "grf.mia",
                                  "grf.Z_true" = "grf.Z_true",
                                  "grf.MDC.mi" = "grf.miwae.agg",
                                  "grf.MDC" = "grf.miwae.zmul")
    
  } else {
    levels(dr.res$method) <- list("loglin.MICE" = "loglin.mice.wy",
                                  "loglin.MF" = "loglin.mf.cv",
                                  "loglin.MDC.process" = "loglin.miwae", 
                                  "loglin.X_true" = "loglin.Z_true",
                                  "loglin.MDC.mi" = "loglin.miwae.agg",
                                  "loglin.MDC" = "loglin.miwae.zmul", 
                                  "grf.MICE" = "grf.mice.wy",
                                  "grf.MF" = "grf.mf.cv",
                                  "grf.MDC.process" = "grf.miwae",
                                  "grf.MIA" = "grf.mia",
                                  "grf.X_true" = "grf.Z_true",
                                  "grf.MDC.mi" = "grf.miwae.agg",
                                  "grf.MDC" = "grf.miwae.zmul")
  }
  
  if (conf$add_mask == "_mask") {print_mask <- "w Mask"} else {print_mask <- "w/o Mask"}
  
  y.max <- conf$y.max#1.2#1.11#min(1.25, max(as.double(dr.res$dr), na.rm=T))
  y.min <- conf$y.min#0.99#0.95#max(0.75, min(as.double(dr.res$dr), na.rm=T))
  
  dr.res$regression <- as.factor(dr.res$regression)
  if (conf$setting =="mf" & conf$link == "nonlinear3"){ dr.res <- dr.res[which(dr.res$regression == "grf"),]}
  
  ggplot(dr.res) +
    geom_boxplot(aes(x=as.character(method), y = as.double(dr), fill = regression)) + 
    colScale + 
    #scale_fill_manual(values = c("#FFDB6D", "#52854C")) +
    geom_hline(yintercept = 1) + 
    theme(axis.text.x= element_text(angle = 60, hjust=1, size=25, face = "bold"),
          axis.text.y= element_text(size=20, face="bold"),
          legend.position = "none") +
    #ggtitle(paste0(conf$prop.missing*100,"% NA, ", conf$setting, ", ", conf$link,", ", print_mask,  ", DR (", length(unique(dr.res$seed))," experiments)")) + 
    ylim(c(y.min, y.max)) +
    #ylim(c(min(0.99,min(as.double(dr.res$dr), na.rm=T)),max(1.05,max(as.double(dr.res$dr), na.rm=T)))) +
    xlab("") +
    ylab("")
  ggsave(paste0(fig.dir, Sys.Date(), "_drago_hopper_",conf$link,"_",conf$setting,
                "_n", conf$n, "_p", conf$p, "_d", d, 
                conf$use.w, "_dmiwae", conf$d.miwae, "_hmiwae", h.miwae, conf$add_mask,
                "_sir", conf$num.samples.sir,
                "_propNA", format(round(conf$prop.missing, 2), nsmall=2),
                "_cit2", as.logical(conf$cit2),
                "_dr_mcar.pdf"), plot = last_plot(),
         width=11, height=8.5)
  
}






