setwd("~/Documents/TraumaMatrix/CausalInference/Simulations/causal-inference-missing/")
source("./load.R")


# >= 13/08: "dlvm" = {confounders are X}, "dlvm2"/"dlvm3" = {confounders are Z}, 
#           "linear1"/"linear2" =  = {confounders are X}, "mf" = {confounders are Z}

data.dir <- "./MissDeepCausal/Synthetic/Data/"
rdata.dir <- "./MissDeepCausal/Synthetic/RData/"
fig.dir <- "./MissDeepCausal/Synthetic/Figures/"

######## Set options

link <- "linear3" # either "linear1"/"linear2"/"linear3"/"nonlinear3" (for "linear1","linear2","mf" setting) or "linear0"/"nonlinear3" (for "dlvm" setting)
setting <- "mf" # either "linear1", "linear2", "mf", "dlvm", "dlvm2" "dlvm3" 
sd <- 0.1 # noise sd for data generation

n <- 5000 # number of realizations
p <- 10 # dimension of the ambient space
d <- 3 # dimension of the latent space
h <- 5 # dimension of hidden units

h.miwae <- 128 # dimension of hidden units used for estimation by MIWAE
add_mask <- "_mask" # either "_mask" or ""  
cit2 <- TRUE
cio2 <- FALSE

mi.m <- 10 # number of multiple imputations
prop.missing = 0.1 # proportion of missing values

num.samples.sir <- 200

###########################################################################
# Load data generated by running script missdeepcausal_comparisons_ate.R
###########################################################################

configurations <- data.frame(rbind(cbind("linear0", "dlvm2", 10000, 0, 10,  FALSE, "mice", "","", TRUE, 200, 0, 4),
                                   cbind("linear0", "dlvm2", 10000, 0.1, 10,  FALSE, "mice", "","", TRUE, 200, 0, 4),
                                   cbind("linear0", "dlvm2", 10000, 0.3, 10,  FALSE, "mice", "","", TRUE, 200, 0, 4)))
                                   # cbind("linear0", "dlvm2", 5000, 0, 10,  FALSE, "mice", "","", TRUE, 200, 0, 4),
                                   # cbind("linear0", "dlvm2", 5000, 0.1, 10,  FALSE, "mice", "","", TRUE, 200, 0, 4),
                                   # cbind("linear0", "dlvm2", 5000, 0.3, 10,  FALSE, "mice", "","", TRUE, 200, 0, 4)))

colnames(configurations) <- c("link","setting",
                              "n", "prop.missing", "d.miwae",
                              "cit2","ci2_imp", "use.w",
                              "add_mask", "offset", "num.samples.sir",
                              "seed.min", "seed.max")

configurations[,c("link","setting",
                  "add_mask", "use.w", 
                  "ci2_imp")] <- apply(configurations[,c("link","setting",
                                                         "add_mask", "use.w",
                                                         "ci2_imp")], 2, as.character)
configurations[,c("prop.missing", "n",
                  "num.samples.sir",
                  "seed.min","seed.max", "d.miwae")] <- sapply(configurations[,c("prop.missing","n",
                                                                                "num.samples.sir",
                                                                                "seed.min","seed.max", "d.miwae")], 
                                                               function(x) as.numeric(as.character(x)))
configurations$cit2 <- as.logical(as.character(configurations$cit2))
configurations$offset <- as.logical(as.character(configurations$offset))

for (i in 1:dim(configurations)[1]){
  conf <- configurations[i,]
  print(conf)
  lin.res <- c()
  seed_seq <- conf$seed.min:conf$seed.max
  for (seed in seed_seq){
    load(file = paste0(rdata.dir, "2019-09-24",
                       "_",conf$link,"_",conf$setting, "_n", conf$n, "_p", p, "_d", d,
                       conf$use.w,"_dmiwae", conf$d.miwae,"_hmiwae", h.miwae,
                       conf$add_mask,
                       "_sir", conf$num.samples.sir,
                       "_propNA", format(round(conf$prop.missing, 2), nsmall=2),
                       "_cit2", as.logical(conf$cit2),
                       "_ci2Imp",conf$ci2_imp,
                       "_offset",conf$offset,
                       "_results_regression_seed",seed,".RData"))
    lin.res <- rbind(lin.res, tau.lin)
    }
  
  lin.res$tau <- as.double(as.character(lin.res$tau))
  
  lin.res <- lin.res[order(as.character(lin.res$method)),] 
  
  lin.res <- lin.res %>%
    filter(!(as.character(method) %in% c("lin.cc", "lin.mice.woy", "lin.mice.wy","lin.miwae.agg","lin.mf.cv")))
  
  lin.res$method <- droplevels(lin.res$method)
  
  if (conf$setting %in% c("mf", "dlvm2", "dlvm3")){
    levels(lin.res$method) <-c("lin.MF", "lin.mean", "lin.MDC.process", "lin.Z_true")
  } else {
    levels(lin.res$method) <-c("lin.MF", "lin.mean", "lin.MDC.process", "lin.X_true")
  }
  
  if (add_mask == "") {print_mask <- "w/o Mask"} else {print_mask <- "w/ Mask"}
  ggplot(lin.res) +
    geom_boxplot(aes(x=as.character(method), y = tau)) + 
    geom_hline(yintercept = 1) + 
    theme(axis.text.x= element_text(angle = 60, hjust=1, size=25, face = "bold"),
          axis.text.y= element_text(size=20, face="bold")) +
    ggtitle(paste0(conf$prop.missing*100,"% NA, ", conf$setting, ", ", conf$link,", ", print_mask, ", linear regression (", length(unique(lin.res$seed))," experiments)")) + 
    ylim(c(0.75, 1.01))+
    #ylim(c(min(0.99,quantile(lin.res$tau, 0.01, na.rm=T)),max(1.01,quantile(lin.res$tau, 0.98, na.rm=T)))) +
    xlab("") +
    ylab("")
  ggsave(paste0(fig.dir, "2019-09-25", "_drago_",conf$link,"_",conf$setting,
                "_n", conf$n, "_p", p, "_d", d, 
                conf$use.w, "_dmiwae", conf$d.miwae, "_hmiwae", h.miwae, conf$add_mask,
                "_sir", conf$num.samples.sir,
                "_propNA", format(round(conf$prop.missing, 2), nsmall=2),
                "_cit2", as.logical(conf$cit2),
                "_offset", as.logical(conf$offset),
                "_lin_regression_mcar.pdf"), plot = last_plot(),
         width=11, height=8.5)

}





