setwd("~/Documents/TraumaMatrix/CausalInference/Simulations/causal-inference-missing/")
source("./load.R")

# >= 13/08: "dlvm" = {confounders are X}, "dlvm2"/"dlvm3" = {confounders are Z}, 
#           "linear1"/"linear2" =  = {confounders are X}, "mf" = {confounders are Z}

data.dir <- "./MissDeepCausal/Synthetic/Data/"
rdata.dir <- "./MissDeepCausal/Synthetic/RData/"
fig.dir <- "./MissDeepCausal/Synthetic/Figures/"

######## Set options

link <- "linear3" # either "linear1"/"linear2"/"linear3"/"nonlinear3" (for "linear1","linear2","mf" setting) or "linear0"/"nonlinear3" (for "dlvm" setting)
setting <- "mf" # either "linear1", "linear2", "mf", "dlvm", "dlvm2" "dlvm3" 
sd <- 0.1 # noise sd for data generation

n <- 5000 # number of realizations
p <- 10 # dimension of the ambient space
d <- 3 # dimension of the latent space
h <- 5 # dimension of hidden units
h.miwae <- 128 # dimension of hidden units used for estimation by MIWAE
add_mask <- "_mask" # either "_mask" or ""  
cit2 <- TRUE
cio2 <- FALSE

mi.m <- 10 # number of multiple imputations
prop.missing = 0.1 # proportion of missing values

num.samples.sir <- 200

###########################################################################
# Load data generated by running script missdeepcausal_comparisons_ate.R
###########################################################################

configurations <- data.frame(rbind(##cbind("nonlinear3", "dlvm2", 5000, 0, 10, FALSE, "", "", "grf", 200, 0, 4),
                                   cbind("nonlinear3", "dlvm2", 5000, 0.1, 10, FALSE, "", "_", "grf", 200, 0, 4),
                                   cbind("nonlinear3", "dlvm2", 5000, 0.3, 10, FALSE, "", "_", "grf", 200, 0, 4),
                                   ##cbind("linear0", "dlvm2", 5000, 0, 10, FALSE, "", "_", "grf", 200, 0, 4),
                                   #cbind("linear0", "dlvm2", 5000, 0.1, 10, FALSE, "", "_", "grf", 200, 0, 4),
                                   #cbind("linear0", "dlvm2", 5000, 0.3, 10, FALSE, "", "_", "grf", 200, 0, 4),
                                   ##cbind("linear3", "mf", 5000, 0, 10, FALSE, "", "_", "grf", 200, 0, 4),
                                   cbind("linear3", "mf", 5000, 0.1, 10, FALSE, "", "_", "grf", 200, 0, 4),
                                   cbind("linear3", "mf", 5000, 0.3, 10, FALSE, "", "_", "grf", 200, 0, 4),
                                   ##cbind("nonlinear3", "dlvm2", 10000, 0, 10, FALSE, "", "_", "grf", 200, 0, 4),
                                   cbind("nonlinear3", "dlvm2", 10000, 0.1, 10, FALSE, "", "_", "grf", 200, 0, 4),
                                   cbind("nonlinear3", "dlvm2", 10000, 0.3, 10, FALSE, "", "_", "grf", 200, 0, 4),
                                   ##cbind("linear3", "mf", 10000, 0, 10, FALSE, "", "_", "grf", 200, 0, 4),
                                   cbind("linear3", "mf", 10000, 0.1, 10, FALSE, "", "_", "grf", 200, 0, 4),
                                   cbind("linear3", "mf", 10000, 0.3, 10, FALSE, "", "_", "grf", 200, 0, 4),
                                   cbind("linear0", "dlvm2", 10000, 0.1, 10, FALSE, "", "_", "grf", 200, 0, 4),
                                   cbind("linear0", "dlvm2", 10000, 0.3, 10, FALSE, "", "_", "grf", 200, 0, 4)))


colnames(configurations) <- c("link","setting","n","prop.missing",
                              "d.miwae","cit2", 
                              "use.w","add_mask", "forest", "num.samples.sir", 
                              "seed.min", "seed.max")

configurations[,c("link","setting","add_mask",
                  "use.w", "forest")] <- apply(configurations[,c("link","setting","add_mask","use.w", "forest")], 2, as.character)
configurations[,c("prop.missing","n",
                  "num.samples.sir",
                  "seed.min","seed.max",
                  "d.miwae")] <- apply(configurations[,c("prop.missing","n",
                                                         "num.samples.sir",
                                                         "seed.min","seed.max",
                                                         "d.miwae")], 2, as.numeric)
configurations$cit2 <- as.logical(configurations$cit2)


for (i in 9:10){#dim(configurations)[1]){
  conf <- configurations[i,]
  print(conf)
  dr.res <- c()
  ipw.res <- c()
  seed_seq <- conf$seed.min:conf$seed.max
  #if (i%in%c(1,3)) {seed_seq <- c(0,1,2,4)}
  for (seed in seed_seq){
    load(file = paste0(rdata.dir, "2019-09-25",
                       "_",conf$link,"_",conf$setting, "_n", conf$n, "_p", p, "_d", d, 
                       conf$use.w,"_dmiwae", conf$d.miwae, "_hmiwae", h.miwae,
                       conf$add_mask,
                       "_sir", conf$num.samples.sir,
                       "_propNA", format(round(conf$prop.missing, 2), nsmall=2),
                       "_cit2", as.logical(conf$cit2), "_ci2Impmice", 
                       "_forest", conf$forest,
                       "_results_dr_ipw_seed",seed,".RData"))
    dr.loglin$dr <- as.double(as.character(dr.loglin$dr))
    dr.loglin$se <- as.double(as.character(dr.loglin$se))
    
    dr.res <- rbind(dr.res, dr.loglin)
  }
  
  dr.res <- dr.res[order(as.character(dr.res$method)),] 
  
  dr.res <- dr.res %>%
    filter((as.character(method) %in% c("loglin.mice.wy", "loglin.mf.cv", "loglin.miwae", 
                                        "loglin.Z_true", "loglin.miwae.agg",
                                        "grf.mice.wy", "grf.mf.cv", "grf.miwae", "grf.mia",
                                        "grf.Z_true", "grf.miwae.agg")))
  dr.res$method <- droplevels(dr.res$method)
  if (conf$setting %in% c("mf", "dlvm2", "dlvm3")){
    levels(dr.res$method) <-c("loglin.MICE", "loglin.MF", "loglin.MDC.process", "loglin.Z_true",
                              "grf.MICE", "grf.MDC.process", "grf.Z_true", "grf.MF", "grf.MIA", "grf.MDC.mi",
                              "loglin.MDC.mi")
  } else {
    levels(dr.res$method) <-c("loglin.MICE", "loglin.MF", "loglin.MDC.process",  "loglin.X_true",
                              "grf.MICE", "grf.MDC.process", "grf.X_true", "grf.MF", "grf.MIA",
                              "grf.MDC.mi",
                              "loglin.MDC.mi")
  }
  
  if (conf$add_mask == "_mask") {print_mask <- "w Mask"} else {print_mask <- "w/o Mask"}
  
  y.max <- 1.01#min(1.25, max(as.double(dr.res$dr), na.rm=T))
  y.min <- 0.75#max(0.75, min(as.double(dr.res$dr), na.rm=T))
  
  ggplot(dr.res) +
    geom_boxplot(aes(x=as.character(method), y = as.double(dr))) + 
    geom_hline(yintercept = 1) + 
    theme(axis.text.x= element_text(angle = 60, hjust=1, size=25, face = "bold"),
          axis.text.y= element_text(size=20, face="bold")) +
    ggtitle(paste0(conf$prop.missing*100,"% NA, ", conf$setting, ", ", conf$link,", ", print_mask,  ", DR (", length(unique(dr.res$seed))," experiments)")) + 
    ylim(c(y.min, y.max)) +
    #ylim(c(min(0.99,min(as.double(dr.res$dr), na.rm=T)),max(1.05,max(as.double(dr.res$dr), na.rm=T)))) +
    xlab("") +
    ylab("")
  ggsave(paste0(fig.dir, "2019-09-25", "_drago_hopper_",conf$link,"_",conf$setting,
                "_n", conf$n, "_p", p, "_d", d, 
                conf$use.w, "_dmiwae", conf$d.miwae, "_hmiwae", h.miwae, conf$add_mask,
                "_sir", conf$num.samples.sir,
                "_propNA", format(round(conf$prop.missing, 2), nsmall=2),
                "_cit2", as.logical(conf$cit2),
                "_dr_mcar.pdf"), plot = last_plot(),
         width=11, height=8.5)
  
}




fit_outcome_glm <- function(X, y, treat){
  df.treated <- data.frame(y = y[which(treat==1)], X = X[which(treat==1),])
  colnames(df.treated) <- c("y", paste("X", 1:dim(X)[2], sep=""))
  df.control <- data.frame(y = y[which(treat==0)], X = X[which(treat==0),])
  colnames(df.control) <- c("y", paste("X", 1:dim(X)[2], sep=""))
  
  df.treated <- df.treated[!duplicated(df.treated[,2:ncol(df.treated)]),]
  one.level.treated <- sapply(df.treated, FUN = function(x) length(unique(x))==1)
  df.treated <- df.treated[,!one.level.treated]
  fmla <- as.formula(paste0("y ~ ", paste( colnames(df.treated[,2:ncol(df.treated)]), collapse= "+")))
  lm.treated <- lm(fmla, data = df.treated)
  
  df.control <- df.control[!duplicated(df.control[,2:ncol(df.control)]),]
  one.level.control <- sapply(df.control, FUN = function(x) length(unique(x))==1)
  df.control <- df.control[,!one.level.control]
  fmla <- as.formula(paste0("y ~ ", paste( colnames(df.control[,2:ncol(df.control)]), collapse= "+")))
  lm.control <- lm(fmla, data = df.control)
  
  colnames(X) <- paste("X", 1:dim(X)[2], sep="")
  y_1.hat <- as.numeric(predict(lm.treated, X[,!one.level.treated[-1]]))
  y_0.hat <- as.numeric(predict(lm.control, X[,!one.level.control[-1]]))
  
  return(data.frame(y_1.hat = y_1.hat, y_0.hat = y_0.hat))
}


