setwd("~/Documents/TraumaMatrix/CausalInference/Simulations/miss-vae/")
library(ggplot2)
library(RColorBrewer)
myColors <- brewer.pal(3,"Set2")
names(myColors) <- c("","grf","glm")
colScale <- scale_fill_manual(name = "",values = rev(myColors))


rdata.dir <- "./results/iclr/"
fig.dir <- "./figures/iclr/"
save_figures <- TRUE

######## Set global variables
d <- 3 # dimension of the latent space
h.miwae <- 128 # dimension of hidden units used for estimation by MIWAE

###########################################################################
# Load data generated by running script missdeepcausal_comparisons_ate.R
###########################################################################
configurations <- data.frame(rbind(
  cbind("nonlinear3", "dlvm2", 5000, 10, 0.1, 3, FALSE, "","", "_", "grf", 200, 0, 9, 0.99, 1.22),
  cbind("linear3", "mf", 5000, 10, 0.1, 3, FALSE, "","", "_", "grf", 200, 0, 9, 0.92, 1.1),
  cbind("linear0", "dlvm2", 5000, 10, 0.1, 3, FALSE, "","", "_", "grf", 200, 0, 9, 0.77, 1.01),
  cbind("nonlinear3", "mf", 5000, 10, 0.1, 3, FALSE, "","", "_", "grf", 200, 0, 9, 0.99, 2.01)))

colnames(configurations) <- c("link","setting","n","p",
                              "prop.missing",
                              "d.miwae","cit2", 
                              "use.w", "use.wy", "add_mask", "forest", "num.samples.sir", 
                              "seed.min", "seed.max",
                              "y.min", "y.max")

configurations[,c("link","setting","add_mask",
                  "use.w","use.wy", "forest")] <- apply(configurations[,c("link","setting","add_mask","use.w","use.wy", "forest")], 2, as.character)
configurations[,c("prop.missing","n", "p",
                  "num.samples.sir",
                  "seed.min","seed.max",
                  "d.miwae",
                  "y.min", "y.max")] <- apply(configurations[,c("prop.missing","n","p",
                                                                "num.samples.sir",
                                                                "seed.min","seed.max",
                                                                "d.miwae",
                                                                "y.min", "y.max")], 2, as.numeric)
configurations$cit2 <- as.logical(configurations$cit2)


for (i in 1:dim(configurations)[1]){
  conf <- configurations[i,]
  print(conf)
  dr.res <- c()
  ipw.res <- c()
  seed_seq <- conf$seed.min:conf$seed.max
  
  for (seed in seed_seq){
    load(file = paste0(rdata.dir,
                       conf$link,"_",conf$setting, "_n", conf$n, "_p", conf$p, "_d", d, 
                       "_hmiwae", h.miwae,
                       "_sir", conf$num.samples.sir,
                       "_propNA", format(round(conf$prop.missing, 2), nsmall=2),
                       "_cit2", as.logical(conf$cit2),
                       "_results_dr_ipw_seed",seed,".RData"))
    dr.loglin$dr <- as.double(as.character(dr.loglin$dr))
    dr.loglin$se <- as.double(as.character(dr.loglin$se))
    
    dr.res <- rbind(dr.res, dr.loglin)
  }
  
  dr.res <- dr.res[order(as.character(dr.res$method)),] 
  
  dr.res <- dr.res %>%
    filter((as.character(method) %in% c("loglin.mice.wy", "loglin.mf", "loglin.miwae", 
                                        "loglin.Z_true", "loglin.miwae.agg",
                                        "grf.mice.wy", "grf.mf", "grf.miwae", "grf.mia",
                                        "grf.Z_true", "grf.miwae.agg")))
  dr.res$method <- droplevels(dr.res$method)
  if (conf$setting %in% c("mf", "dlvm2", "dlvm3")){
    levels(dr.res$method) <- list("loglin.MICE" = "loglin.mice.wy",
                                  "loglin.MF" = "loglin.mf",
                                  "loglin.MDC.process" = "loglin.miwae", 
                                  "loglin.Z_true" = "loglin.Z_true",
                                  "loglin.MDC.mi" = "loglin.miwae.agg",
                                  "loglin.MDC" = "loglin.miwae.zmul", 
                                  "grf.MICE" = "grf.mice.wy",
                                  "grf.MF" = "grf.mf",
                                  "grf.MDC.process" = "grf.miwae",
                                  "grf.MIA" = "grf.mia",
                                  "grf.Z_true" = "grf.Z_true",
                                  "grf.MDC.mi" = "grf.miwae.agg",
                                  "grf.MDC" = "grf.miwae.zmul")
    
  } else {
    levels(dr.res$method) <- list("loglin.MICE" = "loglin.mice.wy",
                                  "loglin.MF" = "loglin.mf.cv",
                                  "loglin.MDC.process" = "loglin.miwae", 
                                  "loglin.X_true" = "loglin.Z_true",
                                  "loglin.MDC.mi" = "loglin.miwae.agg",
                                  "loglin.MDC" = "loglin.miwae.zmul", 
                                  "grf.MICE" = "grf.mice.wy",
                                  "grf.MF" = "grf.mf.cv",
                                  "grf.MDC.process" = "grf.miwae",
                                  "grf.MIA" = "grf.mia",
                                  "grf.X_true" = "grf.Z_true",
                                  "grf.MDC.mi" = "grf.miwae.agg",
                                  "grf.MDC" = "grf.miwae.zmul")
  }
  
  
  y.max <- conf$y.max
  y.min <- conf$y.min
  
  dr.res <- dr.res %>%
                 mutate(regression = if_else(startsWith(as.character(method), "grf."), "grf", "glm"))       
  if (conf$setting =="mf" & conf$link == "nonlinear3"){ dr.res <- dr.res[which(dr.res$regression == "grf"),]}
  
  ggplot(dr.res) +
    geom_boxplot(aes(x=as.character(method), y = as.double(dr), fill = regression)) + 
    colScale + 
    geom_hline(yintercept = 1) + 
    theme(axis.text.x= element_text(angle = 60, hjust=1, size=25, face = "bold"),
          axis.text.y= element_text(size=20, face="bold"),
          legend.position = "none") +
    ylim(c(y.min, y.max)) +
    xlab("") +
    ylab("")
  
  if (save_figures){
    ggsave(paste0(fig.dir, conf$link,"_",conf$setting,
                  "_n", conf$n, "_p", conf$p, "_d", d,
                  "_dmiwae3", "_hmiwae", h.miwae,
                  "_sir", conf$num.samples.sir,
                  "_propNA", format(round(conf$prop.missing, 2), nsmall=2),
                  "_cit2", as.logical(conf$cit2),
                  "_dr_mcar.pdf"), plot = last_plot(),
           width=11, height=8.5)
  }
}






